[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:roadrunner]
command=/usr/local/bin/rr serve -c /var/www/html/.docker/roadrunner/.rr.local.yaml -w /var/www/html
user=www-data
directory=/var/www/html
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
startretries=10
stopasgroup=true

[program:worker]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --queue=default
user=www-data
directory=/var/www/html
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
startretries=10
stopasgroup=true

[program:schedule]
command=php /var/www/html/artisan schedule:work
user=www-data
directory=/var/www/html
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
startretries=10
stopasgroup=true
